# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: acrifsyh7uvf6uis.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t acrifsyh7uvf6uis.azurecr.io/bookjournal:${{ github.sha }}
          docker push acrifsyh7uvf6uis.azurecr.io/bookjournal:${{ github.sha }}
  
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 'Dev'
    needs: build
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            infra:
              - 'azure/**'

      - name: Deploy dev infrastructure
        id: deploy-infra
        if: steps.filter.outputs.infra == 'true'
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./azure/main.bicep
          parameters: ${{ secrets.BICEP_PARAMETERS }}
          failOnStdErr: false

      - name: Deploy app to dev
        id: deploy-app
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bookJournalWebApp-ak4fssfpfqa66'
          images: 'acrifsyh7uvf6uis.azurecr.io/bookjournal:${{ github.sha }}'
  
  deploy-prod:
    runs-on: ubuntu-latest
    environment: 'Production'
    needs: [build, deploy-dev]
    steps:
      - uses: actions/checkout@main
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            infra:
              - 'azure/**'

      - name: Deploy infrastructure
        id: deploy-infra
        if: steps.filter.outputs.infra == 'true'
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./azure/main.bicep
          parameters: ${{ secrets.BICEP_PARAMETERS }}
          failOnStdErr: false
      
      - name: Deploy Azure Front Door
        id: deploy-afd
        if: steps.filter.outputs.infra == 'true'
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./azure/frontdoor.bicep
          parameters: webAppName=${{ steps.deploy-infra.outputs.webAppName}}
          failOnStdErr: false

      - name: Deploy app to staging
        id: deploy-app-staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bookJournalWebApp-y23xitl7od2ku'
          slot-name: staging
          images: 'acrifsyh7uvf6uis.azurecr.io/bookjournal:${{ github.sha }}'
      
      - name: Deploy app to production
        id: deploy-app-production
        run: az webapp deployment slot swap -g BookJournalProd -n bookJournalWebApp-y23xitl7od2ku --slot staging --target-slot production
      
      - run: az logout

